namespace: metallb-system
bases:
- ../../base
commonLabels:
  variant: prod-cluster
patchesStrategicMerge:
- layer2-config.yaml
# # On first install only
# kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
secretGenerator:
- name: memberlist
  files:
  - configs/secretkey
generatorOptions:
 disableNameSuffixHash: true
