apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: datacenter1-ip
      protocol: layer2
      addresses:
      - 192.168.1.26-192.168.1.28
    - name: datacenter2-ip
      protocol: layer2
      addresses:
      - 192.168.2.26-192.168.1.28
    - name: datacenter3-ip
      protocol: layer2
      addresses:
      - 192.168.3.26-192.168.1.28