kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx-dc2
  labels:
    app.kubernetes.io/name: ingress-nginx-dc2
    app.kubernetes.io/part-of: ingress-nginx-dc2
spec:
  loadBalancerIP: 192.168.2.20
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx-dc2
    app.kubernetes.io/part-of: ingress-nginx-dc2
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
